### ISSUE TITLE
Citable Code

### ISSUE THREAD

**Issue by pitmonticone** [bridgewalker/Fastnet.jl#21]
Hi @bridgewalker, you might want to make your repository citable. 

Here are two good resources explaining how to do it: 
* The "Making Your Code Citable" [GitHub Guide](https://guides.github.com/activities/citable-code/) ; 
* The great [video-tutorial](https://www.youtube.com/watch?v=A9FGAU9S9Ow) by @jaantollander.

**Comment by bridgewalker** [comment]
Yes need to do this ...

**Comment by bridgewalker** [comment]
OK done!
