### ISSUE TITLE
Documentation Deployment to GitHub Page

### ISSUE THREAD

**Issue by pitmonticone** [bridgewalker/Fastnet.jl#24]
The documentation [page](https://bridgewalker.github.io/Fastnet.jl/v0.1.1/index.html) doesn't seem to be updated.

**Comment by bridgewalker** [comment]
Yes, focussing on code at the moment. Will update the docs once v0.1.1 is ready. Should be only a few days.

**Comment by pitmonticone** [comment]
Ok great. Thanks.

**Comment by bridgewalker** [comment]
The updated documentation is now uploaded for v0.1.1. Sorry that it took so long. In a few more days 0.1.1 will be the new stable version.

**Comment by pitmonticone** [comment]
No problem at all. Thank you very much!
